onefirewall-wcf-agent:
  image: onefirewall/wcf-agent:v2
  volumes:
    - "/var/log:/var/log:ro"
    - "~/.onefirewall/:/opt/onefirewall/WCF-Agent-latest/config/:ro"
  command: >
    bash -c "
    while true; do node app ids ./config/config.json; node app ips ./config/config.json; sleep 60; done
    "
